# Generated by Django 3.0.2 on 2020-02-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_arif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arif',
        ),
    ]
